/*
 * This source file was generated by the Gradle 'init' task
 */
package cct.luau.cbindings;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
